gandi_api_token: ENC[AES256_GCM,data:Wz9lvY89lJufu5H5jTwkTAUo6dj6AmB2E68aWdZdNnaLAEMOj9Pu/g==,iv:RccbIc+6Hk1+rMamNDZdTJ9Fw80KLE2DKPZxYKD+jy0=,tag:HNgTdW2XPICOXgxO4Swi/w==,type:str]
keycloak_admin_password: ENC[AES256_GCM,data:a2/puPEVkvhv24W5Y6uNb+XZCWiW0bDO/z+0dDvb/w==,iv:IJOcHefOPw/+GgGtkdqC/iT0l1k6vWSc+Q23nhdhcj0=,tag:XEcBCJm2k/NSQ7G9bIfxAw==,type:str]
keycloak_db_password: ENC[AES256_GCM,data:hhW2tNkUUZ5ci4sCVecWWar5jgv3/5u96wax86hn,iv:fdLnPbi8WGlE78Fi3Qt2i/xbD8Yt5XoAiZcUk6tk4ZE=,tag:hs3RKmtRQbIz9Eb7U9bEzg==,type:str]
k3s_token: ENC[AES256_GCM,data:XpiSLMclP/MMdZflkvYGPBpSPQjQERR9y5dFEg2hoNE/t+n5V0iDZ9pd2D1SImtYwu0BDDh1pvwffylnNx3sMQ==,iv:EyuSrOouNGaTAAaS2PUH2xLgzg9TyTyqXxA/sjPxHpA=,tag:GC45B1haG1Ew2TvF8oEGjQ==,type:str]
ghcr_pull_token: ENC[AES256_GCM,data:OddzFnIsrl8TgakLEzYEuJ+nFM/IHHR+RWyrI6Bk9wMMlSk8hae1Lg==,iv:OTnRXaxTLjntQwFvVFqxxObY2DAPKhE1crBf6vpFf0w=,tag:qdN/QSqIXRBrghUZjJMmDw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRzArRmFTUVB5QTdXa0F2
            QzVDRjBZUlVRZXpYVGFtMWFXRHN2alA4ODFzCjBzbEdUM0dJM0VhZ1dEREZZTkFp
            Wjl1L1E2cmVWdmxnQ2wxQXlLcXpTUlkKLS0tIEZlUXc3WnNsMk8xY0hpTnRBc2lW
            ZE5Ec1doS3F6TjloWk5tV24rVWJIMDAK8jBkBf35QrsZzPz9IJ2NiQDj6b+aD88l
            Sfnx8npR+nUeNy/UqfYbz5FTESrCCEviCK4GdKPj+Na6QZtPaSfIqQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ely0mwdy8jawc5zag2td3masfa3xp4hnxv07rzeslykfrr8gqdesv2uexy
    lastmodified: "2026-08-10T00:51:08Z"
    mac: ENC[AES256_GCM,data:ESLl1lqCM6RiONfCVSGyvLlCOf11wMzLgOe0v+amn7IEgAaw78rne5mtu4JT4QvhVbOzFcB7bO9gpiz16kRyZOSYwTPFZlQeZl0lneGik/NjpJRj+vFOMHgbctKzCgjmEOACw+IVRcj2o5tBB0Opa4J0YhTPQYflT2M+oZtuqPU=,iv:G+iuFmabd5VEWfK8VLtzpP+L7L7Q/P9Es/aJwyjmGdY=,tag:W8YmYwkIyxxIA36Qs8HPrg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
