apiVersion: v1
kind: Secret
metadata:
    name: ksops-test
    namespace: ksops-test
stringData:
    hello: ENC[AES256_GCM,data:K3pVcKQ=,iv:E2dBdiDHoaYwCkwB9N7cTpvoaP9pPZUCROFkARNqYg4=,tag:+eK+kPeFOXH/eArXFfBxWQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MlhRNzIzUVlCTHpmYlZx
            b2tMMC8vaUVXNFY0QVJrcEtKWmxTYWEvUmlBCmFmZmRWN25tR0lQajJTTDFFczN4
            bjhUWG1yaWd5b2tYUElqMnUyV0NRWm8KLS0tIFh3YlVhbVVOSExvK0tPK0VsWmYx
            UXpLc1ZPZ2xzUXhhZDZNTWZVbXpqbUUKumbCWdKZMWEovnTn3aSi+oOQj2IxR+aR
            0nYZYq1tequQY7a9+g633DOw4p9DNmpSrXGe3F132FtAKKzUmx75UA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ely0mwdy8jawc5zag2td3masfa3xp4hnxv07rzeslykfrr8gqdesv2uexy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T00:31:12Z"
    mac: ENC[AES256_GCM,data:k2CGLIomJCHoLcK48hwITpOzMJTljoGHPmOFd2EFYxZEAvY3GoymLZhsqiuB987mWEXsCuyGZCsLsuTv7xSZVpoLpjO+eYns8NKZtfQnN3HhRRgKLHlcq7E9FI+CNWMHB1r9tYVLjDE7dVNEYCPgsFC1NNw3+dcjNRSsWJYCC+c=,iv:CcpJ4JRhsEyquW6fEvlr2px8tXcHuNMvIRRyJJKKpIU=,tag:aM1eRoKfhyh2Jy8ZBLOyOw==,type:str]
    version: 3.13.3
