apiVersion: v1
kind: Secret
metadata:
    name: argocd-oidc-secret
    namespace: argocd
    labels:
        app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
    oidc.clientSecret: ENC[AES256_GCM,data:6ep58yvZqaVDu5AiDYs0nYo07FJcxJfL3aMGXFTyviGrP/Zj5XdPsBKlYnz0cdraXPFaiLArZdjfAmSfqvVvFvQPvoWWPkkHmWwNZy9hZuFrl38R01Q=,iv:WIHegLPtgHxKVeiaqXs9hGKnPvn3ns2Ns73YDXtLWx0=,tag:tuAFKtkcXzDpSQ4i1TZpqw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4b0IwY05jN2l1Slg5UnZP
            TjVmTTYxSmtvaGVNSHovTExPUENmV2RBN0FVCjFzb2JDa1B5Um1jVFdacWpRSytK
            MlA1RG01M3dMd2JFMzFBd1RUck55YXMKLS0tIHJnaUhHRGw1RzRlVXNyRTkzamVR
            S1NYdE56Rm9FRm1DR092NDliRjBqUk0KpwIn9iBFa3t9JOfKkY4f2Ar04RT8aOUt
            n1CHTzh4vR4ergvfDdShCyYHJp8gImhjlRQ29RZQJ1eHBCVGV0gewg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ely0mwdy8jawc5zag2td3masfa3xp4hnxv07rzeslykfrr8gqdesv2uexy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T18:11:46Z"
    mac: ENC[AES256_GCM,data:9fcaaohzCnUDUyt1Z2m3OwWB6mhgBGxw53fDFK4G848ay2RA14Dq2OQ7X2TAcyC2dDItbuEWF9emQpBrbjVrTYVUz+G9jxa02Liott1XcDZTrwL+ipv5ufp5uywoT7X2D3l00llqUQLYMuYAlofOtykzpDSW/xaRcDr4LdORFfA=,iv:I8uggqWgujey0ETAI575OI7DK7ODZux8uyFF2MxJabE=,tag:tn7ffoJj+51xhDCiT8QaHg==,type:str]
    version: 3.13.3
