apiVersion: v1
kind: Secret
metadata:
    name: gandi-credentials
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:tB+GN03YeWmObDDbGBNYuq1i0iNdFjmo8UCjBAd4lPbU+kpqPx14Ow==,iv:Z+FO8B524elhDdW/+jNBFhqcaEw87rYnT1QTXyvji6I=,tag:HHrkPgjsEtezNKfWPJOoYg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3L0Y2Si83Z2V1NS8ybkJG
            MTJiV0VBRFBpS2I1bDFCdm9rNTY5elNyM0hJCkFNaElpMGFqd1ZnZEJML2tIdnBV
            VDRJWUJ4aW50VE93NVRWdGhMU0xzS28KLS0tICtValVabElQZFBxazVrZmUySm5r
            VzJYb3FscTFQK1dvcHZFcDdDR3BYbmMKvewdYGgo/OrJLTsaCreZRd7nRKxIHae8
            Soy+94RAifHqJwZe65TvAE4z8ZDymrUCeRB5CGsb57gRvncVkXhHdg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ely0mwdy8jawc5zag2td3masfa3xp4hnxv07rzeslykfrr8gqdesv2uexy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T18:11:46Z"
    mac: ENC[AES256_GCM,data:SU+YG5oJgPT+8T0ioiFV/HCOCpazIZV0G6XwOFZ6MdbUxnxSCEH2oAJpUyH5geeiI7Ts+xb+LlZMBA7gf62PdnoMajgtHEfGWJXmZPba3vrYigcacc5Vn8TxlNiHukUvaD/CYHReLV/eoqyur1ji4zS7VlGIFB7Ae5hmFAHDjoE=,iv:W14cHOGB756Pachs+4ki4laopBXIR2/tUabvIwhkBJo=,tag:bgcy/39YpRFxn+CWXdghkA==,type:str]
    version: 3.13.3
