apiVersion: v1
kind: Secret
metadata:
    name: gitea-oauth-keycloak
    namespace: gitea
type: Opaque
stringData:
    key: ENC[AES256_GCM,data:6PcMypA=,iv:c9VxPKTvFzSOEh/fVgaIBJ3mEIVWyGGCVcVNT0kAnlE=,tag:tZzHp9j9wdV+GoW+YxsBig==,type:str]
    secret: ENC[AES256_GCM,data:cou5DaZFmMToxT9Tyk/5cvzY1kBq7pFUkyxveSWrJsdnpCfWx8oKgnfmnxgEsa70ctMJU1q2l852M20gVRPlfdBP06f0rwmpk79Ikf0p4K++vnkpFGo=,iv:ZXZCtN9P8fN42W+Xvmb4uJWV/uMAwH+k/2c7i5bf84w=,tag:JWhNBcTIPqOq581z7zToeQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Y3Y2UVE4MVdjUlBjbXk1
            V0RnZlJZTFN3UjduOHZkUlBwZ2pQbmZPMVE4CkZSSjA2bjJtRVZsckN4ekx4end1
            eXZrZGNnbGVtWnhhNnRRa0h4cEJ0UU0KLS0tIG1TZVJrZjVDY0VTMkxlalJ2bVU4
            MEtHZG5yMlJITDA0MnFWSjFmczhtTEUKQ1jS+kgcUDJ+R1NMfRVos8WM/kZkrMeD
            DOG5pijm9qG9hGCBfrGki1hdn03fxy0fM+A1/aq6dEICnNv6VzIVmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ely0mwdy8jawc5zag2td3masfa3xp4hnxv07rzeslykfrr8gqdesv2uexy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T18:11:46Z"
    mac: ENC[AES256_GCM,data:uZg3alshltlJj/xFgE9jEfzVWevrTVIgv7TXc2Gx/VKDSC/FlF3TMob4UzL360XdOUsixxsomkTFIClxYlyHjQODlVny7rO8qm047nQLlIHjJ8ufDbUbDfjLvgGT652tkOKJ7BEsccOXsxYJUdZzvQYzE7roK6bDKIx0Lnp12a0=,iv:a/TDd8RvBZg1RzMnCpkVzKabMxoENEAOCnOttNPX1PE=,tag:ZxhsxDRccQQ3pe7UiufQQg==,type:str]
    version: 3.13.3
