apiVersion: v1
kind: Secret
metadata:
    name: gitea-db-secret
    namespace: gitea
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:j6Q7g/TnQBO4ynWiNbeO6JMgswHseXkz,iv:42NoKFWHy7vGgMo98zEBSQ1wE/ZBdmuKj1OyUCMQXTs=,tag:04v+G7FWL4as1poTwdWuRw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjYWI2TTU1cXdxaFpSTG84
            THpVenlISlJhUWdCSWZoeThLcys5OG9vR1RzClB4dmJKbUdsZ0pQZnBtTzU1R3RV
            OG1CZWM0eXpDY1lydWZ2dkRzVm44NHMKLS0tIHFmVVV1NE9mTDNCQmtuTmZrSlo3
            Y3phbHRtUUhzL1ArMGl6UzQwTFRITFUKLh/cP4Q80w4yekMvqjg6sKOmeo9tBBFk
            RR7/PwIwILlQJFiacHjZS0sjg8cY9kXZEt7oqGpTtgPj+D8D4N/j6w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ely0mwdy8jawc5zag2td3masfa3xp4hnxv07rzeslykfrr8gqdesv2uexy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T18:11:46Z"
    mac: ENC[AES256_GCM,data:6RHhI3S8Q2G83VHF0hfpzswKkDOtnFfAWrN7GJxtDX08yJuKIg61cH3Rtl0KxKSVpRYIfY0zQcy9xcw3mGM9TOnpCo8lyRDYMfu45A6Kw1RsEhT3QApPld8FyUJRV1bPt7SmIxAZPE6tTD4a+C8adggUs8/L9BVq3/uCLBSp+iY=,iv:mc+qKmWENddb/7/2bU0AtqizgwQj8KNVhg1kcCIMv5k=,tag:PNnMidIfVPFwwTkPgsNn0g==,type:str]
    version: 3.13.3
