apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:zKnPwYywKs9wXcorWwS3ue7K,iv:iRyzSCN7tpdqTFhVPqgoCE2c5XqMPP2f+o35V8adYp8=,tag:3dlCZS8r2nk6EJKgbVYqeA==,type:str]
    admin-user: ENC[AES256_GCM,data:AR+sK18=,iv:KwpwGS+emB+Ecmpq3olmzerpMXxBW5pB7HJehwE8HFo=,tag:7+vM1ToUPbUjMm4pNjgUfw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VUZJS1FqRXlwNXZZL0wr
            b2lCRktaVWhIVER0UjFkcFNkbUo1ZEc3SUZFCmY3R0FNbHIwVU1XNGtnT3c2YUhx
            clhsUVBNU00vWVI5UHZBbUlrYVFmc3cKLS0tIEJ6RXR5WEpSWG9tV240dE8wa2VP
            dlo1OTlPQlJuQmJjd1JSdjBiSDVZOFEKLGJ+KI9t2w6yUzxy6SR35zmlA3dS24Ya
            KAc8B1s8mwMx9TQTnwa9hKMDj0Uftnod0v+SV13EJxVLEdiq/SVwzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ely0mwdy8jawc5zag2td3masfa3xp4hnxv07rzeslykfrr8gqdesv2uexy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T18:11:46Z"
    mac: ENC[AES256_GCM,data:rMHmXABbOf5P3GPZy+L33qOz6IrFIKuUCXU3QfHC23aaNt2RRkrm6DNudiF9JgxOuOIRgoqBBwNz6q1mVQ+qXIQ9w2/R7rOGdITbzw6FeuyxvvnPI/PQedKvwj7HbCdY8CXhloygHyubqvfYlYZtXiPIiUIlYbZ8iLtPfPR2WTQ=,iv:vWuUfsj2IWpI7twVVcLcYnkwxXTdCZcWILCF53m0nXE=,tag:gH9IOKI3mNtGi9vOI7+sSQ==,type:str]
    version: 3.13.3
