apiVersion: v1
kind: Secret
metadata:
    name: grafana-oidc-secret
    namespace: monitoring
type: Opaque
stringData:
    CLIENT_SECRET: ENC[AES256_GCM,data:JO3MajaPvDZRut/UxvXeozatdyGERznecJe/RGgAN0PrWO/gOIndcPQS2TCrVTeDGR9hDgpdctA80wQXMkjddsva4Kw/9WCbC8Jh01wj3zeyRnp7w2M=,iv:X0bt+Sp9m19PNFMUNmOW2tb8/dj/7aQHp2IiwQKtMZ4=,tag:dispG7r/60dE9l+57LtJKg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvbHloNysraEd3MmlkdUJR
            YTByeGZ2SDZvR0d2WmxFNlRFUzdnUHJ4U1J3Ck9FUEwwczVybkw5akt1eFJEMm9B
            VFlrakllT0JZVGtGYm53cUQ5L3ozYUUKLS0tIFJiTUx5SG5raHJJTStSMm5waDNl
            Q0Nxelh0UDhDSlhiZTkzSEMxV1FHbVkKBgV09O7fDVdar5TSWlRasFvdwN73qEw1
            tAIsvtaBdscbUs7Tp7FzN3J93fMUUxhVr9NyPV3MqkWWXfPgB3pz3A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ely0mwdy8jawc5zag2td3masfa3xp4hnxv07rzeslykfrr8gqdesv2uexy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T18:11:46Z"
    mac: ENC[AES256_GCM,data:JbIsfNUkmbucMCHmrZQq5yrLhmIAj4stDXTPIqeeGoxEtJDb+vB4/Zc7lkrZ094fIX3YLiFq9vaQfQdc2my+UdOD8gSZcdTaa4NMYRNBQW7uIJCWC/xqiJwVsVQTwlb18YH+rbv88eHFzknfJ1XpOzfvJNrihLi2YRXXyJBj+s8=,iv:MAK0Ha+dABICgmpTQPJdQtEVcdFOR/EfRCtoKRiMD74=,tag:7d5VIieb8P0n9k8wts/6gw==,type:str]
    version: 3.13.3
