apiVersion: v1
kind: Secret
metadata:
    name: harbor-admin-secret
    namespace: harbor
type: Opaque
stringData:
    HARBOR_ADMIN_PASSWORD: ENC[AES256_GCM,data:mfLykpSB/AY8OvFrCXKebL6xxrs=,iv:6Z7+4fghCDQCgFfaVLtklxuPZaVpcPom1r070ZvwWYg=,tag:W4AaJYAhpB0ujqCQ/ZjJlA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dEVTVXJ1TWZSNzhhdlM0
            RnlyeG15ZnJ5WUNXaEhsMUltU3lyM0ZweDFFCks5VVlKZm9sb2dkUEh5MkdyQVdi
            OFRnUXI3WXdzODVlY09YdjNoTHlZcW8KLS0tIFhmQmIrR1NueEFSUklwb3BGbVlz
            cWRNQ2d1RW1JL0JGQ3VteG1meEppOFkKpFzPJct56OCTWWJ9GN3Kbsdjo+FcMPSk
            70Ucy+JPXHShV4lJGRk+HwriMbNc6E00Tql0HKIr46wk4J4qfPWDYg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ely0mwdy8jawc5zag2td3masfa3xp4hnxv07rzeslykfrr8gqdesv2uexy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T18:11:46Z"
    mac: ENC[AES256_GCM,data:UVnIoiBcbxaSrsaExX4Jp4A86yN6RdmJ4tD4nyqTL8iOfJQ0jGlYGuRl2RUY9PZEcMVfB9uUf3QaupvuDzwA+RNwWbRIgKYVYW3Rvxb/4R/LOCHThNvPHbH/r+9g3qFp6QRfk0HysaMH+AIvX5zBhsdW+cgZvMgS2hb2ceqKoC4=,iv:UR+QeC7UEzvbBCNIhiTrYoenvYr02uB+r10ArE9VTa8=,tag:vaGc0bYK3psSVblOiYQCMQ==,type:str]
    version: 3.13.3
