apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: netbox-sso-config-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./netbox-sso-config.enc.yaml
