apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: netbox-valkey-fixed-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./netbox-valkey-fixed.enc.yaml
