apiVersion: v1
kind: Secret
metadata:
    name: netbox-sso-config
    namespace: netbox
type: Opaque
stringData:
    sso.py: ENC[AES256_GCM,data:IEm2l2ouYZTTNptCxlIfNF1wtekwcBWturydSnDzrScXPmUcsPSTavzSQrkoyfyFe5GqJCDorCnGFqijNiuxuv5JuVNWyXdgV7GcVIiI5m21NgtCmts+KvxkD8ZtOd92q0315NZzsgl1tpGiUoEKXMEPFaolFo678+7XDx2hGeUfcpliFO6wBXNe3Rk2Tm5DG+Nuh59csW0GYXo2L42NH+NHrD5jIUgax5TbpeIQuVHVZUBDVcOvmPA7nQRAZDqvNjc9iNibchXWOEsVsV4oNEU/95y81cxS92zuccYpnf8=,iv:DFTW3Ld1tHiQYmtbDjlh9vV1ow0LLVqrCRjTFuV5eU0=,tag:1YbLnT7HXHs1m2zxcC4TIA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzM1Z6dXJUUWd3T0RWSTVK
            WDVEbW9YSjlKRGlKRmV3MFU4WXh1TFVpNWtjCm8zWjU4TkJIOUkyL1hDUjdpbUhC
            ajJyWkdMWEpqbW1JR1FDdkwvSGI2Z00KLS0tIHBFVEFCOXBNWkxqZ0lqRVBnUS9R
            Zng1UWlTdWVkREl5TXdXeHRJekdORjAKbmCjyMZYMDNrpSJOIpCYs8i2cZmxfgka
            xBFcYIgiai9t5SzxWtiIZEH4WKSkNjZzoZCaPlMKS/0kpUKiuO2BxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ely0mwdy8jawc5zag2td3masfa3xp4hnxv07rzeslykfrr8gqdesv2uexy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T18:11:46Z"
    mac: ENC[AES256_GCM,data:9iz7OuePnrTWSn49iQRcdL0SXyTmYDpb3YiX2hja57JICZddiafg5SlsVkJ5CRT1tspT46UfGZgfYD/5cz0IsZFgvif2QwOKTH/WIjg7IMEcQqCoLABfmfJT0pLzJBLrUiZQSpb4G+yFdPkY58lMPXayoX7sLGkY8BKjaO2q6YM=,iv:ipH6tlnCFrfd237KfyvSA8gk4X0efu5nH7kbf5B2Nyo=,tag:oFb9DxrCHHLGUmUkD49fYA==,type:str]
    version: 3.13.3
