apiVersion: v1
kind: Secret
metadata:
    name: netbox-superuser
    namespace: netbox
type: kubernetes.io/basic-auth
stringData:
    api_token: ENC[AES256_GCM,data:uVoEXj/QywRtX+WhJDY6/zYt9MqNNb0BjEcX56fT5CPu5QjGFR+o9A==,iv:+lr22v4/YDCP1JLdHh40041NwG4V9+Yuxacg+sg1STw=,tag:zporGCHvDCvTytNFPgAvMw==,type:str]
    email: ENC[AES256_GCM,data:ce2FBeUmvosfEOUgXKmBwoSefbyeCw==,iv:hKdPRipEWD9pv4HNKejHqdowbmCW4oD7fPQuHVGZBvU=,tag:t1CH9wsOHlNdl5U7Nn0x1w==,type:str]
    password: ENC[AES256_GCM,data:URFUqCmr2Q/plXKMZxdcLQbYXWc=,iv:RXGZxRRKtL/mz9rleZbODGSBDqNXKxk/MiZvv1Wq98o=,tag:RTBnXme7A9ubvsW934WdDA==,type:str]
    username: ENC[AES256_GCM,data:TWrWp0s=,iv:fdc2iarxyj70ZeS/8miSsDxbaMLiVr1oTZmsY/FtZN8=,tag:+5iuN37pYskhC8HC7SQ/Ng==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RGplTjNMYnB5aHI3RWtj
            Uk9PeTIzdjNwZHFxNDA2djMzNFlFM0MrNzJrCklCNjd6UVJuSFh4ZXQ5TnlVNzYw
            cE9mdUxYbnhFU1RaNm1BUXZnbnRhZVEKLS0tIGtpdmx2Wll2UGJuNzN6QUJEMTYy
            anF1VWZMRWJNbXJ4WVdYU2xOdFFFa2sKH91EGa3bF+zXoUlG4mGsMQh0dssxuPEF
            iPSzV3lxpx+BiAxpk9UmC7CN/t6pGmlEiGJ8Xpr2CTZ3vrWFxRwLVg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ely0mwdy8jawc5zag2td3masfa3xp4hnxv07rzeslykfrr8gqdesv2uexy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T18:11:46Z"
    mac: ENC[AES256_GCM,data:qn/uXRBLkugkatPIEOpNAyr99CXwecbMXUzaDrDnicMfO3FjfLibJSBkZMc4J1JAr6kHUhQ7fywOiUTQ3ymVvkRvAMnhCBjFWcDl5h+6lDAb74qov1vDp8Qf2Bh+9E2xoIOPlLdnXovDYSuYH6YXXI1i7voHrCT3YaX37/ivanw=,iv:5eM7Bf+WHnum+ki/IibF1u/aZ7O3waTy0WpRkLPUm5A=,tag:yKXgQ9cRo/Py9fuAVv9BTA==,type:str]
    version: 3.13.3
