apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: netbox-superuser-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./netbox-superuser.enc.yaml
