apiVersion: v1
kind: Secret
metadata:
    name: netbox-postgresql-fixed
    namespace: netbox
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:8nrgNlx6bhzHPg==,iv:A6Hp7ip2mjAZzhPKcfFl3fQlYTNTXyzUR7uoWrboglY=,tag:jSSPdBIvLR3VeldgH0hmSw==,type:str]
    postgres-password: ENC[AES256_GCM,data:qmWe4rrPSmWfYSV3NIbOJN5ENXxiadOP37gAzts3c3A=,iv:sJ1sERYnmyw6DuxWQnBFdlzWe5atsVKbMK2QnSRCTeM=,tag:RbwuXulb/FjmP6cGZguiMw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvd3o4OFNNbytjRzgzQTBP
            K05ndXY0dGI4NERzLzU4RjVhaTI5bk9yK0dVCmZPeTA5ZkZ1emVTQTJUMElISGdL
            cUtma0ZqRks5ODI5YlpycHBSSVNhS1EKLS0tIEtTbDdEdXJVUkx0UVFTclByV2NX
            WUsya0sxNS8xU25Sd0RpaTJma2hleEkK8yz2P7GtcMepw4fMk/Ad/Xyt1Ykwn9Rt
            cEzVao02RtvGexkV/V4HIF1uZCW37OgFB7n2mHQ4A7E2IfxY22DGHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ely0mwdy8jawc5zag2td3masfa3xp4hnxv07rzeslykfrr8gqdesv2uexy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T18:11:46Z"
    mac: ENC[AES256_GCM,data:y3u7fI1vEmWzAVKFqvN1wgTFqQrwnDVH7iwI1AwhyzfTINYA8VEXNtJUyRSR8L4hO3aqFgIz+PGPZVsz9WLOZ62tpeGWGrQ/jOnXwjkpwY2TjY72fMPO1q7vx3Xx5OjWkYC8cXyQcLEpvoXEZUzshhJOc37Xc5wtq39aLx7jo4Y=,iv:+Yf2cdUsrSDQiPaWLRDuPYoSUqc/wOXN4CexYdQUzzw=,tag:KU4XQJUMRoaPe4NfTmCGuQ==,type:str]
    version: 3.13.3
