apiVersion: v1
kind: Secret
metadata:
    name: netbox-valkey-fixed
    namespace: netbox
type: Opaque
stringData:
    valkey-password: ENC[AES256_GCM,data:SlMRSk8Id581r3DtCCsoTHi8Q2GqkJY3BTJtU/5vI4Q=,iv:t042TcoWJCWseBucGNjev8TGw9LkAupevOOHBtzv7GU=,tag:LQZQ182RTC+OTxASqiYubg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpeXRaREJTR0ZWYWRtamw1
            bEhmNWJQbnI3ejVxb1NnZEZicERLcHpBWG1NCmJTMXBHM2hIN2s3cWdZd1ZuSzU5
            enNrQ3dvejBTOG4rVkNwMVJzM3Vrc0UKLS0tIEFCYmRQeHQzWnFKc3RabnBYMHVF
            OENuZEQxVFk0ek5DblNqY1poUExBRlkKJ5CVtn0XXPeS6tdDcRDBkMK9sxYSBpr8
            zIhnJd43XwMZk5DI7dhGkdamF322FguYsefuZArfPGHuEgz/xhrLVA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ely0mwdy8jawc5zag2td3masfa3xp4hnxv07rzeslykfrr8gqdesv2uexy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T18:11:47Z"
    mac: ENC[AES256_GCM,data:znlXQ/9OVR7iP9db+Tft2fKo/01FLthNLzEjJpd+04+FQ8CJary8EFby9cGmlapqgtTTlVYvEfg8QBnes+c1BR3diak9/fQwszpk3a9dXO45SeY30PDtESTt6lLXOGr1le043cdKQcw4vz3geaEb2f0IEAd71rc8A24OpZ8fo74=,iv:jbgVsqhIaW/XYTy5y3Dxk+On0CIwEZK+lkrut9QinwQ=,tag:a9x7XktanH0aId+R8XtjoA==,type:str]
    version: 3.13.3
