apiVersion: v1
kind: Secret
metadata:
    name: portal-secrets
    namespace: portal
type: Opaque
stringData:
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:SULorhbMtdtzf8KFuKGDhv7pB9TwBawt8HRBm8u/HOlImVDAwZG8lKCB+BE3ggvN3qVt0MX2to24udG23mJavvMSsoqHGG8DdHQ+8yetnq5ygqgvAw4=,iv:VQdU534HpyQxvyxqyVB3BekN18hVMrvLA0L9pTN1Beo=,tag:VQp8IYDZ/GBB64JmUev52g==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:9n72EycwUvnScV/p3gswo6jk/Y376Dxx4U4d5eCE3t7kmb81o3JB5fBLhJg=,iv:WP/WSB01F9YklDd2DhOqohcX+Q5u6M+06Vl5wYfYPQo=,tag:VO9A/Kd/rwf5Mzf2lt5ZCA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSGFsZWtaTE9Ga2E0anl0
            U29wa25zS0F2cFU5L3pxMzc0bWRzZjRlZm5VCmlIVGkxQ3poRHBpZUtQOGQwNGZK
            dEwyQklMZG5rQkc5STZiWHZKKzZjVkUKLS0tIGs5RU1tb0ZmSFZDNitwLzdDdjFW
            T09VektzelNndU5qVzFIdkc4ajBMZVkKGHEle3ZYI5wMj3hMHuOfDlbejMqld+mA
            F5XhxBqWh4c96Z/+Ry3xl8UuHG7Q+74Xlqk3RucSLaUBI37PTkPv/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ely0mwdy8jawc5zag2td3masfa3xp4hnxv07rzeslykfrr8gqdesv2uexy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T18:11:47Z"
    mac: ENC[AES256_GCM,data:H+w27AbOktF5fVNrm9DcvefjiAyHwTpZMB9eZEhiXDJBdT4YNMJvJR0t1TR/3ak+f9WLyhjcLr1GrcCnCVA/uQMS6U8sJOI3qVjcKeGMyXbRwKmbTHE5KNOuzMrfi74CRhHMliGGJWabe0EcP/Hx4zrg1IgXk26jj0TarpPGbp4=,iv:65j0uSWgfoBdP7wIFaU8hCz0nCR+6BJoFY2brUZ4N4E=,tag:bnMuuAhvgolfxM+HAY5FPw==,type:str]
    version: 3.13.3
