apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: zabbix-db-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./zabbix-db-secret.enc.yaml
