apiVersion: v1
kind: Secret
metadata:
    name: zabbix-db-secret
    namespace: zabbix
type: Opaque
stringData:
    host: ENC[AES256_GCM,data:hT0Gqx/VDSbH3a134yxQ4gk=,iv:ga6r5pdwbG/2XJgzZJRO9xg8XldxQMutdgEOvZ/uUwc=,tag:kLOxFTbPkY0hsE2yctEArA==,type:str]
    port: ENC[AES256_GCM,data:Ox1lBg==,iv:dMIjKkLl5ZJ0j+7DuxSYFJHEEVqy0ep2QP5BtaHg31M=,tag:8jec0hblkIpZmLhOE9xlmA==,type:str]
    user: ENC[AES256_GCM,data:vOfbkrqf,iv:7A2T7yz6gfCDEBX5d/44yuGV72iBmCiAUc3sSTzttew=,tag:2G5cITNgjULqpOQARrj8og==,type:str]
    password: ENC[AES256_GCM,data:pkhqNq8Ku4TZUvR9pTn5drtO1FVFW0X8mMxSzA==,iv:LoJp1F1hT/NXJEz4NSzzly/45/84pFBd5rqDRlrtDSc=,tag:65+rXDGXlQNu1+spjLhXmQ==,type:str]
    dbname: ENC[AES256_GCM,data:675FkY9E,iv:r2+FA7SDaa09qdHgNf1k4XUBd8Ih26IeFNBgIKotqcw=,tag:oSVXp5IQHE1JSBXQc5IJTg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZjdWZHNUcGdaSUcwOVpm
            Q3NueWpvQ1NqelhUR2VaMzF0bjdQYVZEVFdjCkNIcmhNc0VoZzNoaHFKSi9kYjAy
            bm5PRk94bEZOa2RST2t3dHVrZlZrQ0UKLS0tIGdWaURqTHhnODJnSGlrSmNNaDFj
            d2w4dDZrRkg3cGE5U21KUVN1L2x4S3cKOFHxmlZimH1gq+fCNI2/f0WAHKFuNrbE
            3r1N8yM4uw6NnjzSS+F+SulB7g8P4ufRZg9xA5mra5qqTZ/Kls5Qug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ely0mwdy8jawc5zag2td3masfa3xp4hnxv07rzeslykfrr8gqdesv2uexy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T12:44:43Z"
    mac: ENC[AES256_GCM,data:HjgBplctTVJhsFUhZxXG6tOXfovxPoRf+66VmxsDa7azo3p4FPSJKpCMV4H3jGNc/UnTnMPqHkskWowQ2e8reeeT1MHNm6wSb6p4TgvrykgWSt4C1Qk4skWvzHFdEEiCceUtZE8bc0+go88sn4Z9dabLp7p/amWAWFFQlofL+jg=,iv:dnq/ERT2hxdtJ0bPPF96TYFz207G4HTv7/Oo7YJqnVY=,tag:pfxRM85JXRtk1VkqaV6lrA==,type:str]
    version: 3.13.3
