apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: git@github.com:Vanti7/infra-ac.git
    targetRevision: main
    path: kubernetes/secrets
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
