apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: client-edit
  namespace: cust-{{ .Values.name }}
subjects:
  - kind: Group
    name: "oidc:client-{{ .Values.name }}"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
